export const AUTH_USER = 'auth_user'
export const AUTH_REMEMBER = 'auth_remember'
export const AUTH_ERR = 'auth_err'
export const AUTH_GROUPS = 'auth_groups'
export const AUTH_TOKEN = 'auth_token'
export const SET_USER = 'set_user'
export const GET_CUSTOMER = 'get_customer'
export const GET_CUSTOMER_SUBSCRIPTIONS = 'get_customer_subscriptions'
export const GET_CUSTOMER_TRANSACTIONS = 'get_customer_transactions'
export const CREATE_GROUP = 'create_group'

export const GET_GROUP_MEMBERS = 'get_group_members'
export const GET_GROUP_PENDING_MEMBERS = 'get_group_pending_members'
export const GET_GROUP = 'get_group'
export const GET_GROUP_INFO = 'get_group_info'
export const GET_GROUP_EVENT = 'get_group_event'
export const GET_GROUP_EVENTS = 'get_group_events'
export const SET_GROUP_EVENTS = 'set_group_events'
export const CREATE_GROUP_EVENTS_POLL = 'create_group_events_poll'
export const GET_GROUP_EVENT_POLL = 'get_group_event_poll'
export const GET_GROUP_EVENT_POLL_VOTES = 'get_group_event_poll_votes'
export const GET_GROUP_SUGGESTIONS = 'get_group_suggestions'
export const SET_GROUP_SUGGESTIONS = 'set_group_suggestions'
export const GET_GROUP_CHATS = 'get_group_chats'
export const GET_GROUP_CHATS_MESSAGES = 'get_group_chats_messages'
export const SET_GROUP_CHATS_MESSAGES = 'set_group_chats_messages'
export const GET_GROUP_SIGNATURES = 'get_group_signatures'
export const GET_GROUP_SUBSCRIPTION = 'get_group_subscription'
export const SET_NEW_GROUP = 'set_new_group'
export const SELECT_CHAT = 'select_chat'

export const GET_PLANS = 'get_plans'
export const SET_NEW_PLAN = 'set_new_plan'
export const LAST_SIGNATURE = 'last_signature'


export * from './ui.constants'